server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nomad
    username: root
    password: 321456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml